//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleanArchitectureExample.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CleanArchitectureExample.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Guid is empty.
        /// </summary>
        public static string Author_AuthorGuidIsEmpty {
            get {
                return ResourceManager.GetString("Author_AuthorGuidIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Guid is null.
        /// </summary>
        public static string Author_AuthorGuidIsNull {
            get {
                return ResourceManager.GetString("Author_AuthorGuidIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name is null.
        /// </summary>
        public static string Author_AuthorNameIsNull {
            get {
                return ResourceManager.GetString("Author_AuthorNameIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name should have at maximum 100 letters.
        /// </summary>
        public static string Author_AuthorNameNoLongerThantAHundredChars {
            get {
                return ResourceManager.GetString("Author_AuthorNameNoLongerThantAHundredChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author name should have at least 5 letters.
        /// </summary>
        public static string Author_AuthorNameShouldHaveAtLeastFiveChars {
            get {
                return ResourceManager.GetString("Author_AuthorNameShouldHaveAtLeastFiveChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Guid is invalid.
        /// </summary>
        public static string Book_AuthorGuidIsInvalid {
            get {
                return ResourceManager.GetString("Book_AuthorGuidIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Guid string is empty.
        /// </summary>
        public static string Book_AuthorGuidStringIsEmpty {
            get {
                return ResourceManager.GetString("Book_AuthorGuidStringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid author.
        /// </summary>
        public static string Book_AuthorShouldNotBeNull {
            get {
                return ResourceManager.GetString("Book_AuthorShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Guid is empty.
        /// </summary>
        public static string Book_BookGuidIsEmpty {
            get {
                return ResourceManager.GetString("Book_BookGuidIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Guid is invalid.
        /// </summary>
        public static string Book_BookGuidIsInvalid {
            get {
                return ResourceManager.GetString("Book_BookGuidIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Guid is null.
        /// </summary>
        public static string Book_BookGuidIsNull {
            get {
                return ResourceManager.GetString("Book_BookGuidIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition cannot be lowern than 1.
        /// </summary>
        public static string Book_EditionCannotBeLowerThan1 {
            get {
                return ResourceManager.GetString("Book_EditionCannotBeLowerThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books prior 2008 shoud have ISBN with 10 chars long.
        /// </summary>
        public static string Book_ISBNShouldHave10Chars {
            get {
                return ResourceManager.GetString("Book_ISBNShouldHave10Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books latter than 2007 shoud have ISBN with 13 chars long.
        /// </summary>
        public static string Book_ISBNShouldHave13Chars {
            get {
                return ResourceManager.GetString("Book_ISBNShouldHave13Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date cannot be greater than current year.
        /// </summary>
        public static string Book_ReleaseYearCannotBeGraterThanCurrentYear {
            get {
                return ResourceManager.GetString("Book_ReleaseYearCannotBeGraterThanCurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book release date cannot be lower than 1.
        /// </summary>
        public static string Book_ReleaseYearShouldNotBeLowerThan1 {
            get {
                return ResourceManager.GetString("Book_ReleaseYearShouldNotBeLowerThan1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book not found.
        /// </summary>
        public static string Book_ShouldNotBeNull {
            get {
                return ResourceManager.GetString("Book_ShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A book name cannot be empty.
        /// </summary>
        public static string Book_TitleShouldNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("Book_TitleShouldNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Guid is empty.
        /// </summary>
        public static string BookLoan_BookGuidIsEmpty {
            get {
                return ResourceManager.GetString("BookLoan_BookGuidIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Guid is invalid.
        /// </summary>
        public static string BookLoan_BookGuidIsInvalid {
            get {
                return ResourceManager.GetString("BookLoan_BookGuidIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Guid string is empty.
        /// </summary>
        public static string BookLoan_BookGuidStringIsEmpty {
            get {
                return ResourceManager.GetString("BookLoan_BookGuidStringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This book is already lent.
        /// </summary>
        public static string BookLoan_BookIsAlreadyLent {
            get {
                return ResourceManager.GetString("BookLoan_BookIsAlreadyLent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book is not lent.
        /// </summary>
        public static string BookLoan_BookIsNotLent {
            get {
                return ResourceManager.GetString("BookLoan_BookIsNotLent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book not found.
        /// </summary>
        public static string BookLoan_BookIsNull {
            get {
                return ResourceManager.GetString("BookLoan_BookIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book not found.
        /// </summary>
        public static string BookLoan_BookNotFound {
            get {
                return ResourceManager.GetString("BookLoan_BookNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books should be returned within 3 days.
        /// </summary>
        public static string BookLoan_BookShouldBeReturnedWithin3Days {
            get {
                return ResourceManager.GetString("BookLoan_BookShouldBeReturnedWithin3Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book situation should be &apos;Awaiting&apos;.
        /// </summary>
        public static string BookLoan_BookSituationShouldBeAwaiting {
            get {
                return ResourceManager.GetString("BookLoan_BookSituationShouldBeAwaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book situation shoud be &apos;Lent&apos;.
        /// </summary>
        public static string BookLoan_BookSituationShouldBeLent {
            get {
                return ResourceManager.GetString("BookLoan_BookSituationShouldBeLent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person not found.
        /// </summary>
        public static string BookLoan_PersonNotFound {
            get {
                return ResourceManager.GetString("BookLoan_PersonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taker not found.
        /// </summary>
        public static string BookLoan_TakerIsNull {
            get {
                return ResourceManager.GetString("BookLoan_TakerIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Guid is empty.
        /// </summary>
        public static string BookReturn_LoanGuidIsEmpty {
            get {
                return ResourceManager.GetString("BookReturn_LoanGuidIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Guid is invalid.
        /// </summary>
        public static string BookReturn_LoanGuidIsInvalid {
            get {
                return ResourceManager.GetString("BookReturn_LoanGuidIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Guid string is empty.
        /// </summary>
        public static string BookReturn_LoanGuidStringIsEmpty {
            get {
                return ResourceManager.GetString("BookReturn_LoanGuidStringIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document is empty.
        /// </summary>
        public static string Person_DocumentIsEmptyError {
            get {
                return ResourceManager.GetString("Person_DocumentIsEmptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document should have 11 characters.
        /// </summary>
        public static string Person_DocumentWrognCharCount {
            get {
                return ResourceManager.GetString("Person_DocumentWrognCharCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name should have at least 5 letters.
        /// </summary>
        public static string Person_NameMiniumCharError {
            get {
                return ResourceManager.GetString("Person_NameMiniumCharError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person with this document already exists.
        /// </summary>
        public static string Person_PersonWithDocumentExists {
            get {
                return ResourceManager.GetString("Person_PersonWithDocumentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person shoudl shave ate least one related phone number.
        /// </summary>
        public static string Person_ShouldHaveAtLeastOnePhoneNumber {
            get {
                return ResourceManager.GetString("Person_ShouldHaveAtLeastOnePhoneNumber", resourceCulture);
            }
        }
    }
}
